services:

  app:
    build: .
    container_name: smi_parser
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./var/logs:/app/var/logs
    networks:
      - smi_network

networks:
  smi_network:
    driver: bridge
